### ISSUE TITLE
Explain TLS Setup for go 1.15

### ISSUE THREAD

**Issue by bastelfreak** [letsencrypt/unbound_exporter#20] opened 2020-09-25 21:17 UTC
Hi,
since go 1.15 [subject alternative names are required](https://github.com/golang/go/issues/39568). Did you by any chance test your exporter with go 1.15 and know how to create those certs in a way that unbound accepts them?

I created a patch for the unbound-control-setup that successfully creates certificates with a SAN:

```diff
diff --git a/tmp/unbound-control-setup b/usr/sbin/unbound-control-setup
index 3034518..b388186 100755
--- a/tmp/unbound-control-setup
+++ b/usr/sbin/unbound-control-setup
@@ -134,6 +134,8 @@ if [ ! -f "$SVR_BASE.pem" -o $RECREATE -eq 1 ]; then
     openssl req \
             -new -x509 \
             -key "$SVR_BASE.key" \
+            -addext "subjectAltName = DNS:$SERVERNAME" \
+            -addext "certificatePolicies = 1.2.3.4" \
             -config server.cnf  \
             -days "$DAYS" \
             -out "$SVR_BASE.pem"
@@ -169,6 +171,8 @@ if [ ! -f "$CTL_BASE.pem" -o $RECREATE -eq 1 ]; then
 
     openssl req \
             -new \
+            -addext "subjectAltName = DNS:$CLIENTNAME" \
+            -addext "certificatePolicies = 1.2.3.4" \
             -config client.cnf \
             -key "$CTL_BASE.key" \
         | openssl x509 \
```

```
# openssl x509 -in /etc/unbound/unbound_server.pem -text -noout
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            63:d6:f6:92:e3:6c:1c:bc:2c:09:d5:77:9c:ea:9a:0f:c2:39:bc:10
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN = unbound
        Validity
            Not Before: Sep 25 20:38:44 2020 GMT
            Not After : Jun 12 20:38:44 2040 GMT
        Subject: CN = unbound
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (3072 bit)
                Modulus:
                    00:c2:ef:cc:dd:2f:8d:c8:bc:0f:7f:ca:4d:51:f1:
                    23:cb:78:b7:98:b7:23:5e:72:73:3b:8a:af:e0:f7:
                    bf:0c:40:03:66:45:31:12:15:6c:68:cf:6f:e2:41:
                    fd:39:49:87:99:a2:1f:dd:8c:ce:b7:56:2d:28:cc:
                    22:f7:eb:35:31:64:ec:5b:c4:d3:d5:af:42:f8:83:
                    5b:0d:63:81:6c:f5:e5:0d:7c:ae:97:2a:20:13:02:
                    dc:25:c9:fc:9d:19:24:6c:88:99:91:3c:61:6d:55:
                    8e:d8:bd:59:2d:3f:81:5e:77:56:b0:b6:57:2b:1c:
                    7a:d3:be:7c:24:57:ac:0f:7c:e9:6e:e4:61:19:28:
                    24:2f:a4:46:d0:c9:f9:4e:ab:3e:3c:9c:26:76:35:
                    f7:19:76:b1:ad:c0:5b:30:65:54:65:31:27:af:dd:
                    ba:18:77:c8:c0:94:8b:49:d2:0a:7a:ff:33:ea:bf:
                    28:8a:15:96:7b:9e:de:f1:de:08:77:3f:af:47:55:
                    2e:95:71:06:e3:39:62:c7:9b:ee:49:00:7e:5e:0b:
                    bf:61:6c:fb:1a:a5:d0:5d:da:49:47:68:29:c1:9d:
                    87:e7:ac:d6:d6:50:c4:9f:3c:f8:28:3c:0e:fd:db:
                    8e:1e:70:23:79:a1:49:24:67:39:d8:53:ff:8f:ad:
                    03:17:09:5d:a3:e1:1b:79:40:18:4e:e7:f9:8f:16:
                    23:34:8f:5a:67:0c:f2:65:02:9a:38:9b:de:91:48:
                    66:30:b6:12:0b:65:37:ad:7a:79:dc:49:01:9c:0e:
                    1e:a1:2b:bd:92:8e:9e:f8:af:c2:46:59:09:a3:e0:
                    17:cc:db:e2:14:3a:ba:54:16:76:7a:22:fd:70:ff:
                    73:db:79:0d:9b:5c:8a:2b:1f:4f:d9:c2:ee:89:58:
                    b3:13:81:06:eb:30:d3:bc:48:ec:f6:51:36:96:a4:
                    05:db:e1:ef:71:4f:8a:a7:cb:fd:7b:ad:b6:69:37:
                    d4:a3:95:22:57:34:20:58:0a:ef
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Subject Alternative Name: 
                DNS:unbound
            X509v3 Certificate Policies: 
                Policy: 1.2.3.4

    Signature Algorithm: sha256WithRSAEncryption
         2a:2a:a1:b4:f1:26:00:20:fb:a1:0f:71:e7:04:ca:70:f2:9f:
         72:96:ca:db:a1:6a:54:88:6c:3f:1d:57:85:46:1b:6e:b8:7b:
         dc:c1:19:78:3d:18:5b:73:4c:64:a5:de:24:cb:22:a6:29:cc:
         2f:da:df:53:5e:21:f0:6d:73:ef:b5:22:96:9d:0c:8d:8e:9f:
         f2:e8:7c:69:78:be:a9:5a:6e:89:72:d9:4d:bd:57:42:9d:68:
         66:1a:b9:65:36:fa:78:09:7b:c7:6d:e3:45:5d:a6:89:a7:73:
         e6:da:99:fe:26:50:c3:28:02:40:f1:97:09:79:e0:ac:5e:a9:
         89:3c:f1:1b:9c:f1:de:65:ea:2c:f0:ef:67:ae:f8:7e:15:32:
         12:47:e5:c2:48:cb:3b:55:71:b4:93:84:dc:09:bd:f8:b4:82:
         10:3e:3a:10:d9:50:b0:ab:41:7c:03:aa:81:5b:7d:59:f6:d5:
         6b:08:8f:a7:33:dc:c5:67:b9:8d:19:c7:15:03:82:bb:d1:dd:
         73:35:08:ef:fe:ac:16:98:09:4c:ea:f2:bb:df:21:53:e0:3c:
         58:67:fb:da:ad:34:d3:a3:1e:8d:54:33:5a:e7:96:ca:28:06:
         a3:07:e0:0b:28:bc:49:88:ef:82:cd:00:26:ea:46:e9:d3:f4:
         7e:2f:52:17:b7:1b:91:48:19:39:16:8f:e0:86:79:97:00:0e:
         95:6c:6c:ff:0f:08:58:dd:33:54:a9:2f:47:37:15:8f:29:09:
         b3:6d:aa:69:b9:b6:cf:6e:4d:11:65:24:3f:8b:16:ad:31:98:
         64:ce:51:86:b3:1f:3f:4c:58:05:53:17:7b:b5:69:ad:70:12:
         22:4d:08:a7:9d:98:e7:f2:ec:1d:64:b6:ed:b9:3d:77:67:19:
         60:58:a9:c3:7d:22:08:bd:24:2e:a3:f6:69:68:9f:21:e3:05:
         9a:94:e6:1e:74:30:c3:2e:a3:22:0a:8f:d4:44:b2:ed:92:93:
         5b:62:3c:c5:d8:47
```

Sadly unbound doesn't accept it:
```
# ./go/bin/unbound_exporter 
INFO[0000] Starting unbound_exporter                     source="unbound_exporter.go:478"
INFO[0000] Listening on address:port => :9167            source="unbound_exporter.go:496"
ERRO[0004] Failed to scrape socket: %sremote error: tls: unknown certificate authority  source="unbound_exporter.go:459"
```

Do you have any clue on how to get the exporter working on GO 1.15 without disabling the SAN check?

**Comment by jprenken** [comment] 2020-10-06 17:33
This line is also needed in the first segment of the patch:

`-addext "basicConstraints=critical,CA:TRUE,pathlen:0" \`

**Comment by aarongable** [comment] 2021-12-18 00:40
@jprenken can this issue be closed, given that https://github.com/NLnetLabs/unbound/pull/324 has landed, or does something else need to be done here? I ask because I'm not sure if https://github.com/letsencrypt/unbound_exporter/issues/33 is a duplicate of this or not.

**Comment by jprenken** [comment] 2022-07-03 20:45
I'd like to leave this open as a reminder to document how to use the fix, since it's a frequently encountered problem.

**Comment by herbetom** [comment] 2022-10-29 19:01
okay, i was able to get our resolver working again with the following steps:

1. delete old certs:
   ```
   rm /etc/unbound/unbound_server.key /etc/unbound/unbound_server.pem
   rm /etc/unbound/unbound_control.key /etc/unbound/unbound_control.pem
   ```
2. generate new certs:
    ```
    unbound-control-setup
    ```
3. and then restart the unbound and unbound_exporter services:
    ```
    systemctl restart unbound.service
    systemctl restart unbound_exporter.service
    ```

**Closed** 2023-09-22 16:33 UTC
